server:
  port: 0

spring:
  application:
    name: main-service
  dataSource:
    driverClassName: org.postgresql.Driver
    password: sa
    url: jdbc:postgresql://localhost:6543/main-service
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

hibernate:
  jdbc:
    time_zone: UTC
  show_sql: true