server:
  port: 0

spring:
  application:
    name: stats-server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/stats-server
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

hibernate:
  jdbc:
    time_zone: UTC
  show_sql: true
